kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G
org.gradle.warning.mode=all
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.21.11
yarnMappings=1.21.11+build.1
loaderVersion=0.18.4
# Fabric API
fabricVersion=0.141.2+1.21.11
loomVersion=1.15-SNAPSHOT
# Mod Properties
modVersion=2026.3.1
mavenGroup=dev.syoritohatsuki
archivesBaseName=bluemap-custom-skin-server
# Kotlin
systemProp.kotlinVersion=2.3.0
fabricKotlinVersion=1.13.8+kotlin.2.3.0
# Dependencies
blueMapApiVersion=2.7.0
duckyUpdaterVersion=2026.1.1
